### ISSUE TITLE
Feature Request: Excluding fields.

### ISSUE THREAD

**Issue by ozgunozen** [mkorkmaz/soupmix#2]
Hello. 
I think it could be better if the $fields argument of find function accepts an operator to exclude one or more fields and include everything else. Just like filter operations, maybe a "not" operator could be handy. In cases where we have a lot of fields and want to get all the fields except one, I'm wondering if we can write just the field or fields we don't want to get, rather than writing all the other fields we want.

**Comment by mkorkmaz** [comment]
Since excluding specific fields cannot be done on the databases' side for all databases and can be handled by the code side, this feature should be implemented outside of the soupmix.
