### ISSUE TITLE
Feature Request: Get by multiple IDs.

### ISSUE THREAD

**Issue by ozgunozen** [mkorkmaz/soupmix#3]
In a case where I have many IDs and want to get the data. I have to use "get" function for each ID. Instead, if get function can accept multiple IDs, it could be much easier and efficient.

**Comment by mkorkmaz** [comment]
With soupmix/mongodb you can use the the docId argument as an array : 

```
$i  = $m->get('users',['574d5b38a102fd10905a9183','574d5b38a102fd10905a9182']);
```
