### ISSUE TITLE
Update function.

### ISSUE THREAD

**Issue by ozgunozen** [mkorkmaz/soupmix#4]
Update function returns same value for both unsuccessful operations and when there is nothing to update.

After I use update function for editing a data, I control the operation and return something according to the result like below. 

`$updated = $mongo->update("table", $filter, $data);`
`if ($updated > 0){`
`return true;`
`} else {`
`return false;`
`}`

In this case, whether if it has failed because my filter was inaccurate or failed because something else or just nothing to update, I get the same result and return false. But the operation should be considered successful even though there is nothing to update. I think we should be able to know if it's failed or there was nothing to update.

**Comment by mkorkmaz** [comment]
This repository is abandoned since Soupmix moved to its own githun organization. Fixed package can be found at [https://packagist.org/packages/soupmix/mongodb](https://packagist.org/packages/soupmix/mongodb)

FYI, creating an instance is also changed to: 

```
$m=new Soupmix\MongoDB($adapter_config);
```
